void get_account_name args((DESCRIPTOR_DATA *d, char *argument));
void get_account_password args((DESCRIPTOR_DATA *d, char *argument));
void confirm_new_account args((DESCRIPTOR_DATA *d, char *argument));
void get_new_account_password args((DESCRIPTOR_DATA *d, char *argument));
void confirm_new_account_password args((DESCRIPTOR_DATA *d, char *argument));
void get_account_action args((DESCRIPTOR_DATA *d, char *argument));
void show_account args((DESCRIPTOR_DATA *d, char *argument));
void check_attach_password args((DESCRIPTOR_DATA *d, char *argument));
void account_help args((DESCRIPTOR_DATA *d, char *argument));
void save_account args (( ACCOUNT_DATA *account, char *host ));
